plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - cg_codebase.md
  - AboutMe.md
  - excerpts.md
  - MagicalBlog.md
  - MagicalBlog_hidden.md
  - iiith/rrc/writeup_3126.md